# Generated by Django 4.0.2 on 2022-03-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('manufacturerID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('manufacturerName', models.CharField(max_length=15)),
                ('manufacturerAddress', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('orderTime', models.DateTimeField()),
                ('orderTotal', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('productID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('productPrice', models.PositiveIntegerField(default=0)),
                ('productQuantity', models.PositiveIntegerField(default=0)),
                ('productDescription', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('shopID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=50)),
                ('shopAddress', models.CharField(blank=True, default='', max_length=255)),
                ('shopRating', models.FloatField(blank=True, default=0.0)),
                ('shopPhone', models.CharField(blank=True, default='', max_length=50)),
                ('shopDescription', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=15)),
                ('userPhone', models.CharField(blank=True, default='', max_length=50)),
                ('userAddress', models.CharField(blank=True, default='', max_length=255)),
                ('userSex', models.BooleanField(blank=True, default=False)),
                ('userBirthday', models.DateField(blank=True, default='')),
            ],
        ),
    ]
