# Generated by Django 4.0.2 on 2022-03-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_manufacturer_order_product_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productURL',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
