# Generated by Django 4.0.3 on 2022-03-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_product_producturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='cap',
            fields=[
                ('capID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('capProfile', models.CharField(blank=True, default='', max_length=50)),
                ('capMaterial', models.CharField(blank=True, default='', max_length=50)),
                ('capProcess', models.CharField(blank=True, default='', max_length=50)),
                ('capFront', models.CharField(blank=True, default='', max_length=50)),
                ('capPrice', models.IntegerField(default=0)),
                ('CapImageName', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
