# Generated by Django 4.0.3 on 2022-03-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_cap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cap',
            old_name='CapImageName',
            new_name='capFont',
        ),
        migrations.RenameField(
            model_name='cap',
            old_name='capFront',
            new_name='capImageURL',
        ),
    ]
