# Generated by Django 4.0.3 on 2022-03-13 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_rename_capimagename_cap_capfont_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('USER', models.CharField(max_length=50)),
                ('PHONE', models.CharField(blank=True, default='', max_length=50)),
                ('ADDRESS', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('USER', models.CharField(max_length=50)),
                ('PHONE', models.CharField(blank=True, default='', max_length=50)),
                ('ADDRESS', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RESTAURANT', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=50)),
                ('PRICE', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Customer', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Rsestaurant', models.CharField(max_length=50)),
                ('Driver', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Total', models.PositiveIntegerField(default=0)),
                ('Status', models.CharField(max_length=50)),
                ('PickedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('ID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('USER', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=50)),
                ('PHONE', models.CharField(max_length=50)),
                ('ADDRESS', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meal', models.CharField(max_length=50)),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Subtotal', models.PositiveIntegerField(default=0)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.orders')),
            ],
        ),
    ]
