# Generated by Django 4.0.3 on 2022-03-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_customers_drivers_meals_orders_restaurants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='capDescription',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cap',
            name='capName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
